spring.application.name=BiblioBlaBla_Pro

# Pas 'biblio_db' aan naar 'biblioblabla_pro'
spring.datasource.url=jdbc:mysql://localhost:3306/biblioblabla_pro?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Omdat je JDBC gebruikt en geen JPA/Hibernate, zijn deze regels
# eigenlijk niet nodig, maar ze kunnen geen kwaad:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true